### ISSUE TITLE
Message Loss when Nlog Shutdown, Flush did not help

### ISSUE THREAD

**Issue by dolphine1209** [haf/NLog.RabbitMQ#28]
Hi There,

I know this might be not direct a NLog.RabbitMQ issue but rather a NLog issue. When I use a Async wrapper to NLog Targets this always happens. NLog does not shutdown gracefully by flushing all logs. NLog.RabbitMQ is designed to log asynchronously so I think this is even worse. Above all, one choosing to log into RabbitMQ usually means the messages are business-critical. Is there a way to do NLog flush/shutdown w/o losing messages, especially regarding RabbitMQ?

Thanks,

**Comment by haf** [comment]
You could port this to Logary, as Logary provides that facility. One of the reasons I created Logary was because of what you write above.
