### ISSUE TITLE
Unable to use default exchange in rabbitmq

### ISSUE THREAD

**Issue by joakimlemb** [haf/NLog.RabbitMQ#31]
By using exchange="" (aka default exchange), we get the following error in rabbitmq:

=ERROR REPORT==== 4-Nov-2015::13:09:38 ===
Channel error on connection <0.16303.6> (x.x.x.x:53609 -> x.x.x.x:5672, vhost: 'our-vhost', user: 'our-username'), channel 1:
{amqp_error,access_refused,"operation not permitted on the default exchange",
            'exchange.declare'}

I'm guessing the problem is that Nlog.RabbitMQ tries to run "exchange.declare" no matter what instead of checking if exchange exists before running declare?

**Comment by haf** [comment]
I suppose, yes. If you subscribe to the repository you can help me vet PRs in the future to avoid PRs destroying default behaviour.

**Comment by joakimlemb** [comment]
The "bug" is solved for us using the new 2.2.2 version with the passive option committed recently: https://github.com/haf/NLog.RabbitMQ/commit/1fb37f0f52d7f5afc21a5d56d1691aefa5313a02
