### ISSUE TITLE
No compatible with RabbitMQ.Client 3.6

### ISSUE THREAD

**Issue by SenyaMur** [haf/NLog.RabbitMQ#32]
Please upgrade your library for RabbitMQ.Client 3.6. You need change call method IModel.Publish.

**Comment by haf** [comment]
Please send a PR

**Comment by SenyaMur** [comment]
Sorry, but what does it mean "PR"?

**Comment by haf** [comment]
Sorry, it means pull request. I.e. you can do something like this:

```
git clone https://github.com/haf/NLog.RabbitMQ.git
cd NLog.RabbitMQ
update-package
git add . -A
git commit -m "[infra] I updated the client to latest"
git remote add mine git@github.com:SenyaMur/NLog.RabbitMQ.git
git push -u mine master
```

And then come back to github.com (this site) and click the "create pull request" green button.

**Comment by SenyaMur** [comment]
I can't compile your solution, because no have AssemblyVersionInfo.cs file in all projects.

**Comment by haf** [comment]
You need to run `bundle exec rake`, see https://github.com/Albacore/albacore/#albacore-v20
