### ISSUE TITLE
.net 4.5.1 version required on nuget

### ISSUE THREAD

**Issue by DukeCheng** [haf/NLog.RabbitMQ#34]
Do you have a plan to publish the 4.5,4.5.1 and higher version to nuget?

**Comment by haf** [comment]
Only PRs, as I'm not actively maintaining this project. I think you have to make some small fixes to albacore to ensure it can create multiple-framework nugets.

**Comment by DukeCheng** [comment]
@haf I am interesting to continue to maintaining for this project, but how can I participate for this project and nuget package publish?

**Comment by haf** [comment]
You can sort out so that the Rakefile builds what you need and then I can publish that.

**Comment by DukeCheng** [comment]
Looks the Rakefile wrote by Nodejs, do you have any tutorial documents for how to build this?

**Comment by haf** [comment]
Rakefile is ruby, and it's documented [here](https://github.com/Albacore/albacore/wiki)

**Comment by haf** [comment]
Also you should consider that .net is backwards compatible so you generally want to keep the required .net version of nugets down, rather than up.

**Comment by DukeCheng** [comment]
Hi Haf, Thanks, my project have a little urgent, I just resolved the problem and used in my project, if later have time, but I hope I can join this project.
